mysql -uroot -proot  hometeaching2 -e "delete from assign_comps"
mysql -uroot -proot  hometeaching2 -e "delete from assignments"
mysql -uroot -proot  hometeaching2 -e "delete from comps"
mysql -uroot -proot  hometeaching2 -e "delete from district_comps"
mysql -uroot -proot  hometeaching2 -e "delete from family"
mysql -uroot -proot  hometeaching2 -e "delete from member"
